name: bullethole_chess_multiplayer_server
description: Lightweight websocket relay for Bullethole Chess prototype.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  chess: ^0.8.1
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
